### ISSUE TITLE
Performance Issues with Command Preprocessing

### ISSUE THREAD

**Issue by R00tB33rMan** [4drian3d/SignedVelocity#12]
https://spark.lucko.me/Ryze54w182

![image](https://github.com/4drian3d/SignedVelocity/assets/36140389/7c02d76a-bb30-4271-b9bc-8cb6d989577f)

Plugins like MyCommand and DeluxeMenus (plus potentially others) do not bode well with SignedVelocity's command listener. Not exactly sure what to recommend here; however, I'm assuming this may have been an accidental oversight or unexpected occurrence.

**Comment by 4drian3d** [comment]
> https://spark.lucko.me/Ryze54w182
> 
> ![image](https://user-images.githubusercontent.com/36140389/253781380-7c02d76a-bb30-4271-b9bc-8cb6d989577f.png)
> 
> Plugins like MyCommand and DeluxeMenus (plus potentially others) do not bode well with SignedVelocity's command listener. Not exactly sure what to recommend here; however, I'm assuming this may have been an accidental oversight or unexpected occurrence.

What is happening is that for some reason, MyCommand and DeluxeMenus are using the `Player#chat` method to execute commands from the player instead of the [`Server#dispatchCommand`](https://jd.papermc.io/paper/1.20/org/bukkit/Server.html#dispatchCommand(org.bukkit.command.CommandSender,java.lang.String)) or [`Player#performCommand`](https://jd.papermc.io/paper/1.20/org/bukkit/entity/Player.html#performCommand(java.lang.String)) method. This causes the server to consider that the player has actually executed the command on its own, and when going through SignedVelocity's command listener, it waits a maximum of 150 milliseconds on each use of that method for Velocity to send the procedure to execute on that command, but Velocity has never processed that command, so it waits unnecessarily 150 milliseconds and then proceeds with the command execution.
This is a bad implementation of MyCommand and DeluxeMenus by making incorrect use of the Bukkit API. Still, it could be "fixed" from SignedVelocity using a StackWalker, I'll see if I can implement it one of these days.

**Comment by R00tB33rMan** [comment]
Ah! That makes complete sense. I appreciate the far more insightful information regarding this issue. Had a feeling it could have came from one or both parties.

**Comment by R00tB33rMan** [comment]
Hey! I noticed roughly a week ago that you've applied some changes that improve this resource's performance. Could this potentially resolve this presented issue or not at all?

**Comment by 4drian3d** [comment]
> Hey! I noticed roughly a week ago that you've applied some changes that improve this resource's performance. Could this potentially resolve this presented issue or not at all?

Totally, I had planned to mention it in this issue, but I forgot, sorry😅

**Comment by 4drian3d** [comment]
This specific problem was easily solved in SignedVelocity-Sponge as the platform provides APIs to identify these cases. In case of Paper, I still have to try to fix this on my own.
In summary, the performance changes that have been made from BETA 3 to version 1.0.1:
- Reduced the timeout from 150 to 100 milliseconds(could be reduced a bit more, but I need to do a lot more testing).
- In case the player uses a very old version (<1.18.2), it would be possible to cancel the command/message directly from the proxy as there would be no need to handle it from the server.

**Comment by 4drian3d** [comment]
As of the latest version of Paper, commands that are executed incorrectly through the `Player#chat` method will probably no longer be recognized. https://github.com/PaperMC/Paper/pull/8895
This may be very good news for SignedVelocity but may require an update to the plugins you use

**Comment by 4drian3d** [comment]
Could you try the version of pull request #24? According to the tests I did, it fixes the problem by detecting these cases
![](https://cdn.discordapp.com/attachments/914493736891842640/1154276099526762516/image.png)

the test version is published there

**Comment by 4drian3d** [comment]
> Could you try the version of pull request #24? According to the tests I did, it fixes the problem by detecting these cases ![](https://camo.githubusercontent.com/a55967d62411f17548eed438530ebbf90c69f0ab86c4d59862fbb0e1b51b58b6/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3931343439333733363839313834323634302f313135343237363039393532363736323531362f696d6167652e706e67)
> 
> the test version is published there

Tested

**Before:**
![](https://cdn.discordapp.com/attachments/914493736891842640/1155944686704398426/image.png)

**Now:**
![](https://cdn.discordapp.com/attachments/914493736891842640/1155944687056715906/image.png)

**Comment by R00tB33rMan** [comment]
I somehow entirely lost track of this. Looks to be vastly better. Very nice job!
